% This test file was generated by Copilot. Validate generated output before use.
classdef XlsWriteFigTest < matlab.unittest.TestCase
    methods(Test)
        function testWriteNewFile(testCase)
            hFig = figure;
            plot(rand(10,1));
            filename = 'TestFile.xlsx';
            sheetname = 'Sheet1';
            xlcell = 'A1';

            % Call the function
            xlswritefig(hFig, filename, sheetname, xlcell);

            % Verify the file was created
            testCase.verifyTrue(exist(filename, 'file') == 2);

            % Wait a sec for xlswritefig to release the file
            pause(2)

            % Clean up
            delete(filename);
            close(hFig);
        end

        function testWriteToExistingFile(testCase)
            hFig = figure;
            plot(rand(10,1));
            filename = 'ExistingFile.xlsx';
            sheetname = 'Sheet1';
            xlcell = 'A1';

            % Create an existing file
            writematrix("Existing Data", filename, 'Sheet', sheetname);

            % Call the function
            xlswritefig(hFig, filename, sheetname, xlcell);

            % Verify the file still exists
            testCase.verifyTrue(exist(filename, 'file') == 2);

            % Clean up
            delete(filename);
            close(hFig);
        end

        function testInvalidFigureHandle(testCase)
            hFig = figure(Visible = "off");
            close(hFig)
            testCase.verifyError(@() xlswritefig(hFig, 'TestFile.xlsx', 'Sheet1', 'A1'), 'xlswritefig:mustBeFigure');
        end

    end
end